### ISSUE TITLE
set env var with value of split

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-exam#120]
It would be awesome if using `--split=5` would set `process.env.EMBER_EXAM_SPLIT = 5`. Then testem.js setup would be as clean as

```js
  parallel: process.env.EMBER_EXAM_SPLIT,
```

Thoughts?

**Comment by trentmwillis** [comment]
Makes sense to me. PR for this would be welcome!

**Comment by kellyselden** [comment]
Working on it
