### ISSUE TITLE
How to suppress warning?

### ISSUE THREAD

**Issue by samselikoff** [ember-cli/ember-exam#127]
When using ember-exam and running `ember t` we get this warning

> WARNING: An ember-addon has attempted to override the core command "test". The core command will be used.

Any idea how to suppress?

**Comment by trentmwillis** [comment]
Hmm, seems like some detection upstream needs to be refined as this addon does not try to "override" it simply extends the class and registers as a totally new command.

@stefanpenner maybe you can help here?

**Comment by tomwayson** [comment]
This is affecting my addon too, just adding version info in case that's useful:
```
ember-cli: 2.18.0
node: 8.3.0
os: darwin x64
```

**Comment by step2yeung** [comment]
I believe this should be fixed after v3, closing this. @samselikoff Let me know if this isn't true!
