### ISSUE TITLE
Uncaught TypeError: (0 , _load.default) is not a function

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-exam#241]
after trying to update `ember-exam` from v2.0.1 to v2.1.2 we're seeing the following error when trying to run `ember exam --split=8 --parallel`:

```
not ok 1 Chrome 72.0 - [undefined ms] - Global error: Uncaught TypeError: (0 , _load.default) is not a function at http://localhost:4202/assets/tests.js, line 11958
    ---
        Log: |
            { type: 'error',
              testContext: {},
              text: 'Uncaught TypeError: (0 , _load.default) is not a function at http://localhost:4202/assets/tests.js, line 11958\n' }
    ...
```

/cc @stefanpenner

**Comment by step2yeung** [comment]
@Turbo87 check this out: https://github.com/ember-cli/ember-exam#version--210

**Comment by Turbo87** [comment]
@step2yeung that looks like a breaking change to me and should be released as v3.0.0 instead. it also should have been mentioned in the https://github.com/ember-cli/ember-exam/blob/master/CHANGELOG.md file.

**Comment by stefanpenner** [comment]
@step2yeung sorry, i was under the impression this was backwards compatible. Is there a way to make it backwards compat? If not, we may need to re-release your work as 3.x and release a fixed 2.1.2

**Comment by step2yeung** [comment]
@stefanpenner looking into it, will report back shortly
@Turbo87 totally correct, apologies for the breaking change!

**Comment by rwjblue** [comment]
@stefanpenner - While @step2yeung is looking into this, can you re-release 2.0.3 as 2.1.3?
