### ISSUE TITLE
auto-deploy doc site

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-exam#252]
cc @step2yeung as per: https://ember-learn.github.io/ember-cli-addon-docs/docs/deploying#automating-deploys

**Comment by step2yeung** [comment]
@stefanpenner tried to deploy, and I will need permissions & stuff:
```
ERROR: Permission to ember-cli/ember-exam.git denied to step2yeung.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

**Comment by step2yeung** [comment]
@choheekim has updated the addon-docs to be up to date with every release! 
@choheekim thoughts on being able to auto deploy the addon docs as well?

**Comment by choheekim** [comment]
@stefanpenner @step2yeung I have a pr open to deploy addon-docs with every successful merge 
https://github.com/ember-cli/ember-exam/pulls

It hasn't been merged yet but I think the pr will resolve this issue

**Comment by step2yeung** [comment]
Awesome @choheekim!!
Should I merge the PR? https://github.com/ember-cli/ember-exam/pull/405
