### ISSUE TITLE
`--launch` not working and breaking `--parallel` since v3

### ISSUE THREAD

**Issue by enspandi** [ember-cli/ember-exam#268]
The option `--launch=` does not seem to work anymore. It is still working with `ember test --launch=Chrome`, but not ember-exam.

It also seems to run everything in `Examp Partition 1` with `--parallel` option.

Example:
```
ember exam --split=4 --parallel --launch=Chrome
```

**Comment by step2yeung** [comment]
@enspandi 
try `ember exam --split=4 --launch=Chrome --parallel`

**Comment by enspandi** [comment]
yeah that was it :smile:

Thanks!

**Comment by step2yeung** [comment]
awesome! 
The reason is `--parallel` now accepts a param.. so when the cmd is `--parallel --launch=Chrome` --launch=Chrome becomes the value of the `parallel` command.
