### ISSUE TITLE
build once

### ISSUE THREAD

**Issue by lan-nguyen91** [ember-cli/ember-exam#371]
Hi team,

Is there a way to only build ember once when running split and partition. Right now we are trying to run test across containers in CI, but `ember exam --split --partition ...` will run ember build every time. 

While the test is fast, the build is slow and we are building in each container which is very painful. Anyone know of a way to only build once and use the app across container (aka different machine).

**Comment by choheekim** [comment]
Hi, @lan-nguyen91 currently ember-exam doesn't support features to pull build directory to test against across machines :(

**Comment by lan-nguyen91** [comment]
we were able to accomplish this by introduce another step to build the test, save it to CI volume, and use the `--path` to recover it from the volume is each test machine.
