### ISSUE TITLE
Changelog is missing all v4.x releases

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-exam#376]
It looks like the `CHANGELOG.md` file was not maintained for the v4.x releases. If we decided to only use https://github.com/ember-cli/ember-exam/releases then we should delete the file, though ideally we should keep it updated properly.

/cc @step2yeung @choheekim

**Comment by step2yeung** [comment]
@Turbo87 Thanks for calling this out. I'll update `CHANGELOG.md` for the latest releases and keep it up to date going forward!
