### ISSUE TITLE
--parallel appears to only work when it's the last arg

### ISSUE THREAD

**Issue by BenRuns** [ember-cli/ember-exam#408]
I ran into an issue with how the args are consumed

`ember exam --split 25 --reporter dot --parallel` will run the entire suite of tests but

`ember exam --split 25 --parallel --reporter dot` will only run the first partition

This is an issue if you've got your test command as `ember exam --split 25 --parallel` and want to change the reporters through the cli

**Comment by choheekim** [comment]
Please refer [https://github.com/ember-cli/ember-exam/blob/master/README.md#how-to-use] where explains why `--parallel` interprets anything passed after the option as a value for parallel.

After v3.0.1 `parallel` takes arguments to determine number of browsers to launch when running with `load-balance`. To resolve to pass something after `--parallel` I suggest to pass a value e.g.  `ember exam --split 25 --parallel 1 --reporter dot`

**Comment by BenRuns** [comment]
I'll try a number. Parallel true did not appear to work.

**Comment by jakebixbyavalara** [comment]
> I'll try a number. Parallel true did not appear to work.

Yeah, they wired up the argument [as a number](https://github.com/ember-cli/ember-exam/blob/master/lib/commands/exam.js#L36) instead of boolean.

**Comment by BenRuns** [comment]
That worked for me. Still seems unintuitive. It forced me to only use a 1 value, no error was thrown for a string and it seems like the flag should just have a default.

Closing the issue though.

**Comment by step2yeung** [comment]
@BenRuns @jakebixbyavalara I'd agree, in command definition, it does have a type defined as Number, so I guess there isn't a check against that. So some validation might be needed.
