### ISSUE TITLE
--parallel option seems to be sensitive on the next argument

### ISSUE THREAD

**Issue by MichalBryxi** [ember-cli/ember-exam#433]
Following repo:
```
> ember test
...
1..18
# tests 18
# pass  18
# skip  0
# fail  0
```

Will give these different numbers of tests ran based on `--parallel` argument position. I have no idea why the number of tests jumped from 18 to 21 here, but it's still believable that all tests are being run:
```
❯ ember exam --split=4 --partition=1,2,3,4 --parallel
...
1..21
# tests 21
# pass  21
# skip  0
# fail  0
```

In this case however it seems like `--parallel` dislikes the next argument:
```
❯ ember exam --split=4 --parallel --partition=1,2,3,4
...
1..8
# tests 8
# pass  8
# skip  0
# fail  0
```

It is even more weird when I add argument to the `--parallel` switch. Then it again looks ok:
```
❯ ember exam --split=4 --parallel=1 --partition=1,2,3,4
...
1..21
# tests 21
# pass  21
# skip  0
# fail  0
```

Is this a bug in the way arguments are handled?

**Comment by choheekim** [comment]
Hi @MichalBryxi , this issue has been reported and @step2yeung has a fix pr open :) Feel free to review it.
https://github.com/ember-cli/ember-exam/pull/410

**Comment by MichalBryxi** [comment]
Aha! Thank you @choheekim
