### ISSUE TITLE
Embroider Support

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-exam#490]
When I have:
```ts
// tests/test-helper.js
import start from 'ember-exam/test-support/start';
// import { start } from 'ember-qunit';
```
I get the following error at `/tests`:

![image](https://user-images.githubusercontent.com/199018/73611082-4571d180-45ac-11ea-9738-3ed5563f8282.png)

I _think_ this may be a similar issue as: https://github.com/simplabs/qunit-dom/pull/542
cc @ef4

**Comment by ef4** [comment]
I actually happened to hit this same issue in an app this week, and it's on my todo list to debug it.

I don't think ember-exam is doing anything wrong here. It's relying on babel-plugin-module-resolver, which comes with ember-cli-htmlbars, which rewrites `require` with relative paths like that one to full package-absolute paths. 

It looks like either embroider is causing that plugin to get dropped, or embroider's own plugin that rewrites `require` to `window.require` is running first and interrupting babel-plugin-module-resolver from doing the job.

There *is* another blocking bug in ember-exam when it comes to working under embroider, see https://github.com/ember-cli/ember-exam/pull/489
