### ISSUE TITLE
What version of ember cli is required to run with load balancing?

### ISSUE THREAD

**Issue by erikmellum** [ember-cli/ember-exam#543]
The README says you have to be on ember-cli `3.2.0`. When I look at https://github.com/ember-cli/ember-cli it says the most recent release is `3.17.0`. Can someone please clarify what version I'm supposed to be on?

![image](https://user-images.githubusercontent.com/6475033/79399057-2641d980-7f37-11ea-88d5-79ed9ea1a09e.png)

**Comment by choheekim** [comment]
Anything after this release should be compatible for `--load-balance`. https://github.com/ember-cli/ember-cli/releases/tag/v3.2.0

**Comment by erikmellum** [comment]
Thank you!
