### ISSUE TITLE
'ember exam --server' doesn't work with ember-cli 3.19.0 to 3.20.0 update

### ISSUE THREAD

**Issue by sepuckett86** [ember-cli/ember-exam#589]
After updating ember-cli from 3.19.0 to 3.20.0 tests no longer run with `ember exam --server` and this is what is displayed:
```
Randomizing tests with seed: false
process is not captured
```

**Comment by kamilio** [comment]
I am having the same problem while upgrading ember, the stacktrace is pretty much empty.

Unfortunately, can't share repo either.

**Comment by step2yeung** [comment]
Hey @kamilio and @sepuckett86 
I was unable to reproduce this with ember-super-rentals or travis-web.. 
It has ember-cli@3.21.2 and I added ember-exam@5.0.1 and I was unable to reproduce the error.

If you can create a reproduction with a sharable repo or an opensource repo like travis-web, please report back
