### ISSUE TITLE
Magic Number of Parallel

### ISSUE THREAD

**Issue by jrock2004** [ember-cli/ember-exam#597]
Not sure if this is documented anywhere but how do I know which number I set for the number of tests in parallel? Is it based on number of CPU's?

**Comment by step2yeung** [comment]
@jrock2004 good question. This is not stated anywhere, but I think we can add some guidance for this.
We started with basing it off number of cores - 1 (-1 for one core saved for the testem server itself, the rest for browsers). We had a very very large test suite (35k+ tests) so we needed max out the number of cores to speed up the parallelization as much as possible.
 
Over time, we found our CI boxes would spike in both core and memory utilization, which caused some tests to behave non-deterministically. By reducing the number of cores used by 40%, we achieved a good balance of speed and stability.

So it does need some experimentation to figure out what works for you.

**Comment by jrock2004** [comment]
Thank you. I think this would be a nice section to add to documentation
