### ISSUE TITLE
Could not find module `qunit` imported from `(require)`

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-exam#634]
In https://github.com/rust-lang/crates.io/pull/3080 we are trying to upgrade crates.io to use ember-qunit v5, but it appears like ember-exam might be incompatible currently. It seems to work fine when running `ember test` regularly, but when `ember test` is run via embroider (`USE_EMBROIDER=true`) then the test runner never progresses. When doing the same with `ember serve` and visiting `/tests` the following error appears on the console:

```
Uncaught Error: Could not find module `qunit` imported from `(require)`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at requireModule (loader.js:24)
    at eval (qunit.js:1)
    at Object.../externals/qunit.js (chunk.9a41034696370d422cb6.js:187)
    at __webpack_require__ (chunk.9a41034696370d422cb6.js:80)
    at eval (ember-exam-qunit-test-loader.js:9)
    at Module../node_modules/ember-exam/test-support/-private/ember-exam-qunit-test-loader.js (chunk.4592e8d4fc35b4d1b9b8.js:740)
    at __webpack_require__ (chunk.9a41034696370d422cb6.js:80)
    at getTestLoader (get-test-loader.js:13)
```

/cc @rwjblue

**Comment by rwjblue** [comment]
Met with @thoov about this earlier, we have a path forward:

* Add `ember-auto-import` as a dependency
* Conditionally add `qunit` to `autoImport.excludes` when using ember-qunit@4

Something like:

```js
  init() {
    this._super.init.apply(this, arguments);

    // ...snip...

    this.options = this.options || {};
    this.options.autoImport = {
      exclude: [],
    };

    // TODO: remove this (and the additional exclude below) once we are certain
    // that we will only test against ember-qunit >= 5
    const hasMagicallyProvidedQUnit = this._versionChecker
      .for('ember-qunit')
      .lt('5.0.0-beta.1');

    if (hasMagicallyProvidedQUnit) {
      this.options.autoImport.exclude.push('qunit');
    }
  }
```

**Comment by wagenet** [comment]
I think we may be seeing the same issue with slightly different manifestation. We're getting `QUnit` is not defined in our test server.

**Comment by rwjblue** [comment]
@wagenet - `QUnit` is not defined generally means something is attempting to use the `window.QUnit` global without importing/requiring it (and is usually different from what @Turbo87 is reporting here).

**Comment by wagenet** [comment]
@rwjblue I think you’re right. I’m pretty sure ember-exam is not actually our issue.
